//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjektAplikacji
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DataBaseEntities : DbContext
    {
        public DataBaseEntities()
            : base("name=DataBaseEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<magazyn_firmy> magazyn_firmy { get; set; }
        public virtual DbSet<magazyn_kategorie> magazyn_kategorie { get; set; }
        public virtual DbSet<magazyn_lista> magazyn_lista { get; set; }
        public virtual DbSet<magazyn_produkty> magazyn_produkty { get; set; }
        public virtual DbSet<sprzedaz_klienci> sprzedaz_klienci { get; set; }
        public virtual DbSet<sprzedaz_pracownicy> sprzedaz_pracownicy { get; set; }
        public virtual DbSet<sprzedaz_sklepy> sprzedaz_sklepy { get; set; }
        public virtual DbSet<sprzedaz_zamowienia> sprzedaz_zamowienia { get; set; }
        public virtual DbSet<sprzedaz_zamowione_rzeczy> sprzedaz_zamowione_rzeczy { get; set; }
    }
}
