//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjektAplikacji
{
    using System;
    using System.Collections.Generic;
    
    public partial class magazyn_lista
    {
        public int sklep_id { get; set; }
        public int produkt_id { get; set; }
        public Nullable<int> ilosc { get; set; }
    
        public virtual magazyn_produkty magazyn_produkty { get; set; }
        public virtual sprzedaz_sklepy sprzedaz_sklepy { get; set; }
    }
}
