//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjektAplikacji
{
    using System;
    using System.Collections.Generic;
    
    public partial class magazyn_produkty
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public magazyn_produkty()
        {
            this.magazyn_lista = new HashSet<magazyn_lista>();
            this.sprzedaz_zamowione_rzeczy = new HashSet<sprzedaz_zamowione_rzeczy>();
        }
    
        public int produkt_id { get; set; }
        public string produkt_nazwa { get; set; }
        public int firma_id { get; set; }
        public int kategoria_id { get; set; }
        public string model_rok { get; set; }
        public decimal cena { get; set; }
    
        public virtual magazyn_firmy magazyn_firmy { get; set; }
        public virtual magazyn_kategorie magazyn_kategorie { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<magazyn_lista> magazyn_lista { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<sprzedaz_zamowione_rzeczy> sprzedaz_zamowione_rzeczy { get; set; }
    }
}
