//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjektAplikacji
{
    using System;
    using System.Collections.Generic;
    
    public partial class sprzedaz_zamowienia
    {
        public int zamowienie_id { get; set; }
        public Nullable<int> klient_id { get; set; }
        public byte zamowienie_status { get; set; }
        public System.DateTime zamowienia_data { get; set; }
        public Nullable<System.DateTime> wysylka_data { get; set; }
        public int sklep_id { get; set; }
        public int pracownik_id { get; set; }
    
        public virtual sprzedaz_klienci sprzedaz_klienci { get; set; }
        public virtual sprzedaz_sklepy sprzedaz_sklepy { get; set; }
        public virtual sprzedaz_zamowione_rzeczy sprzedaz_zamowione_rzeczy { get; set; }
    }
}
