//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjektAplikacji
{
    using System;
    using System.Collections.Generic;
    
    public partial class sprzedaz_pracownicy
    {
        public int pracownik_id { get; set; }
        public string imie { get; set; }
        public string nazwisko { get; set; }
        public string email { get; set; }
        public string telefon { get; set; }
        public int sklep_id { get; set; }
        public int menadzer_id { get; set; }
    
        public virtual sprzedaz_sklepy sprzedaz_sklepy { get; set; }
    }
}
