//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjektAplikacji
{
    using System;
    using System.Collections.Generic;
    
    public partial class sprzedaz_zamowione_rzeczy
    {
        public int zamowienie_id { get; set; }
        public int produkt_id { get; set; }
        public int ilosc { get; set; }
        public decimal cena { get; set; }
        public decimal przecena { get; set; }
    
        public virtual magazyn_produkty magazyn_produkty { get; set; }
        public virtual sprzedaz_zamowienia sprzedaz_zamowienia { get; set; }
    }
}
